/* Generated By:JavaCC: Do not edit this line. KarloffConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int VOID = 8;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int BOOL = 10;
  /** RegularExpression Id. */
  int VAR = 11;
  /** RegularExpression Id. */
  int PV = 12;
  /** RegularExpression Id. */
  int LPAR = 13;
  /** RegularExpression Id. */
  int RPAR = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int THEN = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int REPEAT = 18;
  /** RegularExpression Id. */
  int UNTIL = 19;
  /** RegularExpression Id. */
  int RETURN = 20;
  /** RegularExpression Id. */
  int OUTPUT = 21;
  /** RegularExpression Id. */
  int FUNC = 22;
  /** RegularExpression Id. */
  int TRUE = 23;
  /** RegularExpression Id. */
  int FALSE = 24;
  /** RegularExpression Id. */
  int NUM = 25;
  /** RegularExpression Id. */
  int ID = 26;
  /** RegularExpression Id. */
  int SUM = 27;
  /** RegularExpression Id. */
  int SUB = 28;
  /** RegularExpression Id. */
  int MUL = 29;
  /** RegularExpression Id. */
  int DIV = 30;
  /** RegularExpression Id. */
  int ATR = 31;
  /** RegularExpression Id. */
  int EQ = 32;
  /** RegularExpression Id. */
  int LESS = 33;
  /** RegularExpression Id. */
  int GREATER = 34;
  /** RegularExpression Id. */
  int OR = 35;
  /** RegularExpression Id. */
  int AND = 36;
  /** RegularExpression Id. */
  int SEPARATOR = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"void\"",
    "\"int\"",
    "\"bool\"",
    "\"newVar\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"if\"",
    "\"then\"",
    "\"while\"",
    "\"repeat\"",
    "\"until\"",
    "\"return\"",
    "\"System.output\"",
    "\"func\"",
    "\"true\"",
    "\"false\"",
    "<NUM>",
    "<ID>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"|\"",
    "\"&\"",
    "\",\"",
  };

}
